use_frameworks!

target "HeliarHexpressAPPLojista" do
# NativeScriptPlatformSection /Users/runner/work/HeliarHexpress.APPLojista/HeliarHexpress.APPLojista/app/App_Resources/iOS/Podfile
# End NativeScriptPlatformSection

# Begin Podfile - /Users/runner/work/HeliarHexpress.APPLojista/HeliarHexpress.APPLojista/node_modules/@nativescript/core/platforms/ios/Podfile
use_frameworks!

pod 'MaterialComponents/Tabs', '~> 94.5'
# End Podfile

# Begin Podfile - /Users/runner/work/HeliarHexpress.APPLojista/HeliarHexpress.APPLojista/node_modules/nativescript-image/platforms/ios/Podfile
pod 'SDWebImage', '>= 5.0.6'

# End Podfile

# Begin Podfile - /Users/runner/work/HeliarHexpress.APPLojista/HeliarHexpress.APPLojista/node_modules/nativescript-imagepicker/platforms/ios/Podfile
pod 'QBImagePickerController', '~> 3.4.0'
# End Podfile

# Begin Podfile - /Users/runner/work/HeliarHexpress.APPLojista/HeliarHexpress.APPLojista/node_modules/nativescript-iqkeyboardmanager/platforms/ios/Podfile
pod 'IQKeyboardManager', '~> 6.2.0'

# End Podfile

# Begin Podfile - /Users/runner/work/HeliarHexpress.APPLojista/HeliarHexpress.APPLojista/node_modules/nativescript-plugin-firebase/platforms/ios/Podfile

#pod 'Firebase/Core', '~>6.16.0'

# Analytics
pod 'Firebase/Analytics'

# Authentication
#pod 'Firebase/Auth'

# Realtime DB
#pod 'Firebase/Database'

# Cloud Firestore
pod 'Firebase/Firestore'

# Remote Config
#pod 'Firebase/RemoteConfig'

# Performance Monitoring
#pod 'Firebase/Performance'

# Crashlytics
#pod 'Fabric'
#pod 'Crashlytics'


# Firebase Cloud Messaging (FCM)
pod 'Firebase/Messaging'

# Firebase In-App Messaging
#pod 'Firebase/InAppMessaging'

# Firebase Cloud Storage
#pod 'Firebase/Storage'

# Firebase Cloud Functions
#pod 'Firebase/Functions'

# AdMob
#pod 'Firebase/AdMob'

# Dynamic Links
#pod 'Firebase/DynamicLinks'

# ML Kit
#pod 'Firebase/MLVision'
#pod 'Firebase/MLVisionTextModel'
#pod 'Firebase/MLVisionBarcodeModel'
#pod 'Firebase/MLVisionFaceModel'
#pod 'Firebase/MLVisionLabelModel'
#pod 'Firebase/MLVisionObjectDetection'
#pod 'Firebase/MLModelInterpreter'
#pod 'Firebase/MLVisionAutoML'
#pod 'Firebase/MLNaturalLanguage'
#pod 'Firebase/MLNLLanguageID'
#pod 'Firebase/MLNLTranslate'
#pod 'Firebase/MLCommon'
#pod 'Firebase/MLNLSmartReply'

# Facebook Authentication
#pod 'FBSDKCoreKit'
#pod 'FBSDKLoginKit'

# Google Authentication
#pod 'GoogleSignIn', '~> 5.0'
# End Podfile

# Begin Podfile - /Users/runner/work/HeliarHexpress.APPLojista/HeliarHexpress.APPLojista/node_modules/nativescript-secure-storage/platforms/ios/Podfile
pod 'SAMKeychain', '~> 1.5.3'
# End Podfile

post_install do |pi|
    pi.pods_project.targets.each do |t|
        t.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        end
    end
end
end