on:
  push:
    branches:
      - masterIOS
name: 🚀 Deploy website on push
jobs:
  build:
    name: 🎉 Deploy
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install six  
        run: pip install six
        
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - uses: apple-actions/import-codesign-certs@v1
        with: 
            p12-filepath: './Certificates.p12'
            p12-password: APPLE@@2023 
 
      - name: Provisioning Profiles 
        run: | 
            mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles 
            echo "List profiles"
            ls ~/Library/MobileDevice/Provisioning\ Profiles/ 
            echo "Move profiles"
            cp ./Heliar_Express_Dev.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/  
            cp ./Heliar_Express_Dev_AdHoc.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/ 
            echo "List profiles"
            ls ~/Library/MobileDevice/Provisioning\ Profiles/ 

      - name: Install nativescript
        run: |
          npm install -g nativescript@v6.8
          sudo pip install --upgrade pip 
          pip install --user --upgrade matplotlib 
          pip install six  
          tns doctor
        
      - name: Build IOS release 
        run: tns build ios --for-device --env.production --provision 7cd0e1db-8bf6-4341-a96a-b84dd56c254f 

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ./sorvetes.homolog.co/
